CREATE TABLE public.users (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	active bool NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	modified_at timestamp(6) NOT NULL,
	modified_by varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	refresh_token varchar(255) NULL,
	reset_token varchar(255) NULL,
	"role" varchar(255) NOT NULL,
	CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['A'::character varying, 'C'::character varying, 'D'::character varying, 'W'::character varying, 'K'::character varying])::text[])))
);