CREATE TABLE public.products (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	category varchar(255) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by varchar(255) NOT NULL,
	description varchar(255) NULL,
	image_url varchar(255) NULL,
	is_active bool NOT NULL,
	modified_at timestamp(6) NOT NULL,
	modified_by varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	price float8 NOT NULL,
	CONSTRAINT products_category_check CHECK (((category)::text = ANY ((ARRAY['AP'::character varying, 'MC'::character varying, 'SD'::character varying, 'DR'::character varying, 'DE'::character varying])::text[]))),
	CONSTRAINT products_pkey PRIMARY KEY (id)
);