CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    price DOUBLE PRECISION NOT NULL CHECK (price > 0),
    category VARCHAR(50) NOT NULL CHECK (category IN ('AP', 'MC', 'SD', 'DR', 'DE')),
    available BOOLEAN NOT NULL,
    image_url VARCHAR(255),
    created_by VARCHAR(255) NOT NULL,
    modified_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    modified_at TIMESTAMP NOT NULL
);