CREATE TABLE public.orders (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by varchar(255) NOT NULL,
	modified_at timestamp(6) NOT NULL,
	modified_by varchar(255) NOT NULL,
	status varchar(255) NOT NULL,
	total_price float8 NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT orders_pkey PRIMARY KEY (id),
	CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PE'::character varying, 'AP'::character varying, 'RE'::character varying, 'OW'::character varying, 'DN'::character varying, 'DY'::character varying, 'CA'::character varying])::text[])))
);